# Generated by Django 3.2.5 on 2021-07-26 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_Candidato', models.CharField(max_length=100)),
                ('phone', models.PositiveIntegerField(blank=True)),
                ('usuario', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_curriculum', models.CharField(max_length=100)),
                ('formacao', models.CharField(max_length=100)),
                ('candidato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vagasApp.candidato')),
            ],
        ),
        migrations.CreateModel(
            name='Vagas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disponiveis', models.PositiveIntegerField()),
                ('total', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=200)),
                ('cargo', models.CharField(max_length=100)),
                ('tempo', models.PositiveIntegerField()),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vagasApp.curriculum')),
            ],
        ),
    ]
