# Generated by Django 3.2.5 on 2021-07-28 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vagasApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidato',
            old_name='nome_Candidato',
            new_name='nome_candidato',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='senha',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='curriculum',
            name='formacao',
        ),
        migrations.RemoveField(
            model_name='curriculum',
            name='name_curriculum',
        ),
        migrations.RemoveField(
            model_name='vagas',
            name='disponiveis',
        ),
        migrations.RemoveField(
            model_name='vagas',
            name='total',
        ),
        migrations.AddField(
            model_name='candidato',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='area_formacao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='grau_de_instrucao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='nome_curriculum',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vagas',
            name='cargo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vagas',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vagas',
            name='empresa',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vagas',
            name='vagas_ofertadas',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
