# Generated by Django 3.2.5 on 2021-07-28 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vagasApp', '0002_auto_20210728_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='candidato',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vagasApp.candidato'),
        ),
    ]
